// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_YvGfl3OVLcn25TWAnDBxF1E47EAxKFc',
    appId: '1:614556023089:web:a0f782cfb20c8fd1add810',
    messagingSenderId: '614556023089',
    projectId: 'taskflow-e58bf',
    authDomain: 'taskflow-e58bf.firebaseapp.com',
    storageBucket: 'taskflow-e58bf.firebasestorage.app',
    measurementId: 'G-RJ1TN1HDH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKwoA_KcPzpr8btRJN-2jkPvpzeSG34FE',
    appId: '1:614556023089:android:6da3e0439e1f12e6add810',
    messagingSenderId: '614556023089',
    projectId: 'taskflow-e58bf',
    storageBucket: 'taskflow-e58bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMdB0mTpyP8i75fMSQoSZ-kWnWVPnkBzk',
    appId: '1:614556023089:ios:6fc1b91cef40863eadd810',
    messagingSenderId: '614556023089',
    projectId: 'taskflow-e58bf',
    storageBucket: 'taskflow-e58bf.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMdB0mTpyP8i75fMSQoSZ-kWnWVPnkBzk',
    appId: '1:614556023089:ios:6fc1b91cef40863eadd810',
    messagingSenderId: '614556023089',
    projectId: 'taskflow-e58bf',
    storageBucket: 'taskflow-e58bf.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_YvGfl3OVLcn25TWAnDBxF1E47EAxKFc',
    appId: '1:614556023089:web:7506fa1c6ad7f922add810',
    messagingSenderId: '614556023089',
    projectId: 'taskflow-e58bf',
    authDomain: 'taskflow-e58bf.firebaseapp.com',
    storageBucket: 'taskflow-e58bf.firebasestorage.app',
    measurementId: 'G-P65ZTYSQBZ',
  );
}
